1.1.6-7: do not insert family mismatched/empty inline set rules

diff --git a/files/etc/init.d/pbr b/files/etc/init.d/pbr
--- a/files/etc/init.d/pbr
+++ b/files/etc/init.d/pbr
@@ -1226,29 +1226,12 @@ traffic_killswitch() {
 
 # original idea by @egc112: https://github.com/egc112/OpenWRT-egc-add-on/tree/main/stop-dns-leak
 dns_policy_routing() {
-	local mark i nftInsertOption='add'
-	local param4_tcp param4_udp param6_tcp param6_udp
-	local negation value dest4 dest6
-	local dest_dns_interface dest_dns_ipv4 dest_dns_ipv6
+	local mark i nftInsertOption='add' proto='tcp udp' proto_i
+	local param4 param6
+	local negation value dest4 dest6 first_value
+	local inline_set_ipv4_empty_flag inline_set_ipv6_empty_flag
 	local name="$1" src_addr="$2" dest_dns="$3" uid="$4"
 	local chain='dstnat_lan' iface='dns'
-
-	dest_dns_interface="$(str_first_value_interface "$dest_dns")"
-	dest_dns_ipv4="$(str_first_value_ipv4 "$dest_dns")"
-	dest_dns_ipv6="$(str_first_value_ipv6 "$dest_dns")"
-
-	if is_supported_interface "$dest_dns_interface"; then
-		local d
-		for d in $(uci -q get network."$dest_dns_interface".dns); do
-			if ! is_family_mismatch "$src_addr" "$d"; then
-				if is_ipv4 "$d"; then
-					dest_dns_ipv4="${dest_dns_ipv4:-$d}"
-				elif is_ipv6 "$d"; then
-					dest_dns_ipv6="${dest_dns_ipv6:-$d}"
-				fi
-			fi
-		done
-	fi
 
 	if [ -z "${dest_dns_ipv4}${dest_dns_ipv6}" ]; then
 		processPolicyError='true'
@@ -1262,70 +1245,87 @@ dns_policy_routing() {
 		return 1
 	fi
 
-	if is_family_mismatch "$(str_first_word "$src_addr")" "$dest_dns_ipv4" && \
-		is_family_mismatch "$(str_first_word "$src_addr")" "$dest_dns_ipv6"; then 
+	if { is_ipv4 "$(str_first_word "$src_addr")" && [ -z "$dest_dns_ipv4" ]; } || \
+		{ is_ipv6 "$(str_first_word "$src_addr")" && [ -z "$dest_dns_ipv6" ]; }; then 
 		processPolicyError='true'
 		state add 'errorSummary' 'errorPolicyProcessMismatchFamily' "${name}: '$src_addr' '$dest_dns'"
 		return 1
 	fi
 
-	dest4="dport 53 counter dnat ip to ${dest_dns_ipv4}:53"
-	dest6="dport 53 counter dnat ip6 to ${dest_dns_ipv6}:53"
+	for proto_i in $proto; do
+		unset param4
+		unset param6
 
-	if [ -n "$src_addr" ]; then
-		if [ "${src_addr:0:1}" = "!" ]; then
-			negation='!='; value="${src_addr:1}"; nftset_suffix='_neg';
-		else
-			unset negation; value="$src_addr"; unset nftset_suffix;
-		fi
-		first_value="$(str_first_word "$value")"
-		if is_phys_dev_quick "$first_value"; then
-			param4="${param4:+$param4 }iifname ${negation:+$negation }{ $(inline_set "$value") }"
-			param6="${param6:+$param6 }iifname ${negation:+$negation }{ $(inline_set "$value") }"
-		elif is_mac_address "$first_value"; then
-			param4="${param4:+$param4 }ether saddr ${negation:+$negation }{ $(inline_set "$value") }"
-			param6="${param6:+$param6 }ether saddr ${negation:+$negation }{ $(inline_set "$value") }"
-		elif is_domain "$first_value"; then
-			param4="${param4:+$param4 }${nftIPv4Flag} saddr ${negation:+$negation }{ $(inline_set_resolve_ipv4 "$value") }"
-			param6="${param6:+$param6 }${nftIPv6Flag} saddr ${negation:+$negation }{ $(inline_set_resolve_ipv6 "$value") }"
-		else
-			param4="${param4:+$param4 }${nftIPv4Flag} saddr ${negation:+$negation }{ $(inline_set "$value") }"
-			param6="${param6:+$param6 }${nftIPv6Flag} saddr ${negation:+$negation }{ $(inline_set "$value") }"
-		fi
-	fi
+		dest4="dport 53 counter dnat ip to ${dest_dns_ipv4}:53"
+		dest6="dport 53 counter dnat ip6 to ${dest_dns_ipv6}:53"
 
-	param4_tcp="$nftInsertOption rule inet ${nftTable} ${nftPrefix}_${chain} ${param4} tcp ${dest4} comment \"$name\""
-	param4_udp="$nftInsertOption rule inet ${nftTable} ${nftPrefix}_${chain} ${param4} udp ${dest4} comment \"$name\""
-	param6_tcp="$nftInsertOption rule inet ${nftTable} ${nftPrefix}_${chain} ${param6} tcp ${dest6} comment \"$name\""
-	param6_udp="$nftInsertOption rule inet ${nftTable} ${nftPrefix}_${chain} ${param6} udp ${dest6} comment \"$name\""
-	local ipv4_error='0' ipv6_error='0'
-	{ nft4 "$param4_tcp" && nft4 "$param4_udp"; } || ipv4_error='1'
-	{ nft6 "$param6_tcp" && nft6 "$param6_udp"; } || ipv6_error='1'
-	if [ -n "$ipv6_enabled" ] && [ "$ipv4_error" -eq '1' ] && [ "$ipv6_error" -eq '1' ]; then
-		processPolicyError='true'
-		state add 'errorSummary' 'errorPolicyProcessInsertionFailed' "$name"
-		state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param4_tcp"
-		state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param4_udp"
-		state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param6_tcp"
-		state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param6_udp"
-		logger -t "$packageName" "ERROR: nft $param4_tcp"
-		logger -t "$packageName" "ERROR: nft $param4_udp"
-		logger -t "$packageName" "ERROR: nft $param6_tcp"
-		logger -t "$packageName" "ERROR: nft $param6_udp"
-	elif [ -z "$ipv6_enabled" ] && [ "$ipv4_error" -eq '1' ]; then
-		processPolicyError='true'
-		state add 'errorSummary' 'errorPolicyProcessInsertionFailedIpv4' "$name"
-		state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param4_tcp"
-		state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param4_udp"
-		logger -t "$packageName" "ERROR: nft $param4_tcp"
-		logger -t "$packageName" "ERROR: nft $param4_udp"
-	fi
+		if [ -n "$src_addr" ]; then
+			if [ "${src_addr:0:1}" = "!" ]; then
+				negation='!='; src_addr="${src_addr//\!}"; nftset_suffix='_neg';
+			else
+				unset negation; unset nftset_suffix;
+			fi
+			value="$src_addr"
+			first_value="$(str_first_word "$value")"
+			if is_phys_dev_quick "$first_value"; then
+				param4="${param4:+$param4 }iifname ${negation:+$negation }{ $(inline_set "$value") }"
+				param6="${param6:+$param6 }iifname ${negation:+$negation }{ $(inline_set "$value") }"
+			elif is_mac_address "$first_value"; then
+				param4="${param4:+$param4 }ether saddr ${negation:+$negation }{ $(inline_set "$value") }"
+				param6="${param6:+$param6 }ether saddr ${negation:+$negation }{ $(inline_set "$value") }"
+			elif is_domain "$first_value"; then
+				local inline_set_ipv4 inline_set_ipv6
+				inline_set_ipv4="$(inline_set_resolve_ipv4 "$value")"
+				inline_set_ipv6="$(inline_set_resolve_ipv6 "$value")"
+				[ -n "$inline_set_ipv4" ] || inline_set_ipv4_empty_flag='true'
+				[ -n "$inline_set_ipv6" ] || inline_set_ipv6_empty_flag='true'
+				param4="${param4:+$param4 }${nftIPv4Flag} saddr ${negation:+$negation }{ $inline_set_ipv4 }"
+				param6="${param6:+$param6 }${nftIPv6Flag} saddr ${negation:+$negation }{ $inline_set_ipv6 }"
+			else
+				param4="${param4:+$param4 }${nftIPv4Flag} saddr ${negation:+$negation }{ $(inline_set "$value") }"
+				param6="${param6:+$param6 }${nftIPv6Flag} saddr ${negation:+$negation }{ $(inline_set "$value") }"
+			fi
+		fi
+
+		param4="$nftInsertOption rule inet ${nftTable} ${nftPrefix}_${chain} ${param4} ${proto_i} ${dest4} comment \"$name\""
+		param6="$nftInsertOption rule inet ${nftTable} ${nftPrefix}_${chain} ${param6} ${proto_i} ${dest6} comment \"$name\""
+
+		local ipv4_error='0' ipv6_error='0'
+		if [ "$policy_routing_nft_prev_param4" != "$param4" ]; then
+			if [ -n "$first_value" ] && ! is_ipv6 "$first_value" && [ -z "$inline_set_ipv4_empty_flag" ]; then
+				nft4 "$param4" || ipv4_error='1'
+				policy_routing_nft_prev_param4="$param4"
+			fi
+		fi
+		if [ "$policy_routing_nft_prev_param6" != "$param6" ] && \
+			[ "$param4" != "$param6" ]; then
+			if [ -n "$first_value" ] && ! is_ipv4 "$first_value" && [ -z "$inline_set_ipv6_empty_flag" ]; then
+				nft6 "$param6" || ipv6_error='1'
+				policy_routing_nft_prev_param6="$param6"
+			fi
+		fi
+
+		if [ -n "$ipv6_enabled" ] && [ "$ipv4_error" -eq '1' ] && [ "$ipv6_error" -eq '1' ]; then
+			processPolicyError='true'
+			state add 'errorSummary' 'errorPolicyProcessInsertionFailed' "$name"
+			state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param4"
+			state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param6"
+			logger -t "$packageName" "ERROR: nft $param4"
+			logger -t "$packageName" "ERROR: nft $param6"
+		elif [ -z "$ipv6_enabled" ] && [ "$ipv4_error" -eq '1' ]; then
+			processPolicyError='true'
+			state add 'errorSummary' 'errorPolicyProcessInsertionFailedIpv4' "$name"
+			state add 'errorSummary' 'errorPolicyProcessCMD' "nft $param4"
+			logger -t "$packageName" "ERROR: nft $param4"
+		fi
+	done
 }
 
 policy_routing() {
 	local mark i nftInsertOption='add'
 	local param4 param6 proto_i negation value dest4 dest6
-	local nftset_suffix first_value
+	local nftset_suffix first_value_src first_value_dest
+	local inline_set_ipv4_empty_flag inline_set_ipv6_empty_flag
 	local name="$1" iface="$2" src_addr="$3" src_port="$4" dest_addr="$5" dest_port="$6" proto chain uid="$9"
 	proto="$(str_to_lower "$7")"
 	chain="$(str_to_lower "$8")"
@@ -1386,20 +1386,25 @@ policy_routing() {
 
 		if [ -n "$src_addr" ]; then
 			if [ "${src_addr:0:1}" = "!" ]; then
-				negation='!='; value="${src_addr:1}"; nftset_suffix='_neg';
+				negation='!='; value="${src_addr//\!}"; nftset_suffix='_neg';
 			else
 				unset negation; value="$src_addr"; unset nftset_suffix;
 			fi
-			first_value="$(str_first_word "$value")"
-			if is_phys_dev_quick "$first_value"; then
+			first_value_src="$(str_first_word "$value")"
+			if is_phys_dev_quick "$first_value_src"; then
 				param4="${param4:+$param4 }iifname ${negation:+$negation }{ $(inline_set "$value") }"
 				param6="${param6:+$param6 }iifname ${negation:+$negation }{ $(inline_set "$value") }"
-			elif is_mac_address "$first_value"; then
+			elif is_mac_address "$first_value_src"; then
 				param4="${param4:+$param4 }ether saddr ${negation:+$negation }{ $(inline_set "$value") }"
 				param6="${param6:+$param6 }ether saddr ${negation:+$negation }{ $(inline_set "$value") }"
-			elif is_domain "$first_value"; then
-				param4="${param4:+$param4 }${nftIPv4Flag} saddr ${negation:+$negation }{ $(inline_set_resolve_ipv4 "$value") }"
-				param6="${param6:+$param6 }${nftIPv6Flag} saddr ${negation:+$negation }{ $(inline_set_resolve_ipv6 "$value") }"
+			elif is_domain "$first_value_src"; then
+				local inline_set_ipv4 inline_set_ipv6
+				inline_set_ipv4="$(inline_set_resolve_ipv4 "$value")"
+				inline_set_ipv6="$(inline_set_resolve_ipv6 "$value")"
+				[ -n "$inline_set_ipv4" ] || inline_set_ipv4_empty_flag='true'
+				[ -n "$inline_set_ipv6" ] || inline_set_ipv6_empty_flag='true'
+				param4="${param4:+$param4 }${nftIPv4Flag} saddr ${negation:+$negation }{ $inline_set_ipv4 }"
+				param6="${param6:+$param6 }${nftIPv6Flag} saddr ${negation:+$negation }{ $inline_set_ipv6 }"
 			else
 				param4="${param4:+$param4 }${nftIPv4Flag} saddr ${negation:+$negation }{ $(inline_set "$value") }"
 				param6="${param6:+$param6 }${nftIPv6Flag} saddr ${negation:+$negation }{ $(inline_set "$value") }"
@@ -1408,23 +1413,28 @@ policy_routing() {
 
 		if [ -n "$dest_addr" ]; then 
 			if [ "${dest_addr:0:1}" = "!" ]; then
-				negation='!='; value="${dest_addr:1}"; nftset_suffix='_neg';
+				negation='!='; value="${src_addr//\!}"; nftset_suffix='_neg';
 			else
 				unset negation; value="$dest_addr"; unset nftset_suffix;
 			fi
-			first_value="$(str_first_word "$value")"
-			if is_phys_dev_quick "$first_value"; then
+			first_value_dest="$(str_first_word "$value")"
+			if is_phys_dev_quick "$first_value_dest"; then
 				param4="${param4:+$param4 }oifname ${negation:+$negation }{ $(inline_set "$value") }"
 				param6="${param6:+$param6 }oifname ${negation:+$negation }{ $(inline_set "$value") }"
-			elif is_domain "$first_value"; then
+			elif is_domain "$first_value_dest"; then
 				local target='dst' type='ip'
 				if resolver 'create_resolver_set' "$iface" "$target" "$type" "$uid" "$name" && \
 					resolver 'add_resolver_element' "$iface" "$target" "$type" "$uid" "$name" "$value"; then
 					param4="${param4:+$param4 }${nftIPv4Flag} daddr ${negation:+$negation }@${nftPrefix}_${iface}_4_${target}_${type}_${uid}${nftset_suffix}"
 					param6="${param6:+$param6 }${nftIPv6Flag} daddr ${negation:+$negation }@${nftPrefix}_${iface}_6_${target}_${type}_${uid}${nftset_suffix}"
 				else
-					param4="${param4:+$param4 }${nftIPv4Flag} daddr ${negation:+$negation }{ $(inline_set_resolve_ipv4 "$value") }"
-					param6="${param6:+$param6 }${nftIPv6Flag} daddr ${negation:+$negation }{ $(inline_set_resolve_ipv6 "$value") }"
+					local inline_set_ipv4 inline_set_ipv6
+					inline_set_ipv4="$(inline_set_resolve_ipv4 "$value")"
+					inline_set_ipv6="$(inline_set_resolve_ipv6 "$value")"
+					[ -n "$inline_set_ipv4" ] || inline_set_ipv4_empty_flag='true'
+					[ -n "$inline_set_ipv6" ] || inline_set_ipv6_empty_flag='true'
+					param4="${param4:+$param4 }${nftIPv4Flag} daddr ${negation:+$negation }{ $inline_set_ipv4 }"
+					param6="${param6:+$param6 }${nftIPv6Flag} daddr ${negation:+$negation }{ $inline_set_ipv6 }"
 				fi
 			else
 				param4="${param4:+$param4 }${nftIPv4Flag} daddr ${negation:+$negation }{ $(inline_set "$value") }"
@@ -1486,12 +1496,12 @@ policy_routing() {
 			param4="$nftInsertOption rule inet $nftTable ${nftPrefix}_${chain} $param4 $dest4 comment \"$name\""
 			param6="$nftInsertOption rule inet $nftTable ${nftPrefix}_${chain} $param6 $dest6 comment \"$name\""
 			local ipv4_error='0' ipv6_error='0'
-			if [ "$policy_routing_nft_prev_param4" != "$param4" ]; then
+			if [ "$policy_routing_nft_prev_param4" != "$param4" ] && [ -z "$inline_set_ipv4_empty_flag" ]; then
 				nft4 "$param4" || ipv4_error='1'
 				policy_routing_nft_prev_param4="$param4"
 			fi
 			if [ "$policy_routing_nft_prev_param6" != "$param6" ] && \
-				[ "$param4" != "$param6" ]; then
+				[ "$param4" != "$param6" ] && [ -z "$inline_set_ipv6_empty_flag" ]; then
 				nft6 "$param6" || ipv6_error='1'
 				policy_routing_nft_prev_param6="$param6"
 			fi
@@ -1521,6 +1531,23 @@ dns_policy_process() {
 	src_addr="$(str_extras_to_space "$src_addr")"
 	dest_dns="$(str_extras_to_space "$dest_dns")"
 
+	local dest_dns_interface dest_dns_ipv4 dest_dns_ipv6
+	dest_dns_interface="$(str_first_value_interface "$dest_dns")"
+	dest_dns_ipv4="$(str_first_value_ipv4 "$dest_dns")"
+	dest_dns_ipv6="$(str_first_value_ipv6 "$dest_dns")"
+	if is_supported_interface "$dest_dns_interface"; then
+		local d
+		for d in $(uci -q get network."$dest_dns_interface".dns); do
+			if ! is_family_mismatch "$src_addr" "$d"; then
+				if is_ipv4 "$d"; then
+					dest_dns_ipv4="${dest_dns_ipv4:-$d}"
+				elif is_ipv6 "$d"; then
+					dest_dns_ipv6="${dest_dns_ipv6:-$d}"
+				fi
+			fi
+		done
+	fi
+
 	unset processDnsPolicyError
 	output 2 "Routing '$name' DNS to $dest_dns "
 	if [ -z "$src_addr" ]; then
@@ -1534,10 +1561,18 @@ dns_policy_process() {
 
 	# group by type of src_addr values so that one nft set can be created per type within policy
 	local filter_list_src_addr='phys_dev phys_dev_negative mac_address mac_address_negative domain domain_negative ipv4 ipv4_negative ipv6 ipv6_negative'
-	local filtered_value_src_addr
-	for filtered_value_src_addr in $filter_list_src_addr; do
-		filtered_value_src_addr=$(filter_options "$filtered_value_src_addr" "$src_addr")
+	local filter_group_src_addr filtered_value_src_addr
+	for filter_group_src_addr in $filter_list_src_addr; do
+		filtered_value_src_addr=$(filter_options "$filter_group_src_addr" "$src_addr")
 		if [ -n "$src_addr" ] && [ -n "$filtered_value_src_addr" ]; then
+			if { [ "$filter_group_src_addr" = 'ipv4' ] || [ "$filter_group_src_addr" = 'ipv4_negative' ]; } && \
+				[ -z "$dest_dns_ipv4" ] ; then
+					continue
+			fi
+			if { [ "$filter_group_src_addr" = 'ipv6' ] || [ "$filter_group_src_addr" = 'ipv6_negative' ]; } && \
+				[ -z "$dest_dns_ipv6" ] ; then
+					continue
+			fi
 			dns_policy_routing "$name" "$filtered_value_src_addr" "$dest_dns" "$uid"
 		fi
 	done
@@ -1603,15 +1638,23 @@ policy_process() {
 
 	local filter_list_src_addr='phys_dev phys_dev_negative mac_address mac_address_negative domain domain_negative ipv4 ipv4_negative ipv6 ipv6_negative'
 	local filter_list_dest_addr='domain domain_negative ipv4 ipv4_negative ipv6 ipv6_negative'
-	local filtered_value_src_addr filtered_value_dest_addr
+	local filter_group_src_addr filtered_value_src_addr filter_group_dest_addr filtered_value_dest_addr
 	[ -z "$src_addr" ] && filter_list_src_addr='none'
-	for filtered_value_src_addr in $filter_list_src_addr; do
-		filtered_value_src_addr=$(filter_options "$filtered_value_src_addr" "$src_addr")
+	for filter_group_src_addr in $filter_list_src_addr; do
+		filtered_value_src_addr=$(filter_options "$filter_group_src_addr" "$src_addr")
 		if [ -z "$src_addr" ] || { [ -n "$src_addr" ] && [ -n "$filtered_value_src_addr" ]; }; then
 			[ -z "$dest_addr" ] && filter_list_dest_addr='none'
-			for filtered_value_dest_addr in $filter_list_dest_addr; do
-				filtered_value_dest_addr=$(filter_options "$filtered_value_dest_addr" "$dest_addr")
+			for filter_group_dest_addr in $filter_list_dest_addr; do
+				filtered_value_dest_addr=$(filter_options "$filter_group_dest_addr" "$dest_addr")
 				if [ -z "$dest_addr" ] || { [ -n "$dest_addr" ] && [ -n "$filtered_value_dest_addr" ]; }; then
+					if { [ "$filter_group_src_addr" = 'ipv4' ] || [ "$filter_group_src_addr" = 'ipv4_negative' ]; } && \
+						{ [ "$filter_group_dest_addr" = 'ipv6' ] || [ "$filter_group_dest_addr" = 'ipv6_negative' ]; }; then
+							continue
+					fi
+					if { [ "$filter_group_src_addr" = 'ipv6' ] || [ "$filter_group_src_addr" = 'ipv6_negative' ]; } && \
+						{ [ "$filter_group_dest_addr" = 'ipv4' ] || [ "$filter_group_dest_addr" = 'ipv4_negative' ]; }; then
+							continue
+					fi
 					policy_routing "$name" "$interface" "$filtered_value_src_addr" "$src_port" "$filtered_value_dest_addr" "$dest_port" "$proto" "$chain" "$uid"
 				fi
 			done
